### ISSUE TITLE
Directed network and adjacency matrix

### ISSUE THREAD

**Issue by moranges** [srikanthBezawada/AdjacencyMatrixExporter#1]
Hi,

I've created a directed network in Cytoscape from scratch, or at least I think I did. When I export its adjacency matrix thru the Export... menu, I get one that does not reflect the direction of the arrows.

Can you please help me with this? Basically I need to understand if the adj exporter plugin is the one that doesn't support this or if I'm doing something wrong when creating the network.

Thank you so much,

Mariano P. Oranges.

**Comment by smd-faizan** [comment]
Hi,

Yes, right now we support only undirected graphs i.e. all the edges are considered as undirected edges. Adj-Exporter currently does not support your use-case.

We are glad that you reported this to us. According to your requirement, we will work upon this enhancement. Please let us know if this is urgent. We will try to resolve this issue as soon as possible.

Thanks,
Shaik Mohammed Faizaan 

developers only:
changes to be done in the _createAdjMatrix_ method of the class - 
[https://github.com/srikanthBezawada/AdjacencyMatrixExporter/blob/master/src/main/java/org/cytoscape/adj/writer/AdjNetworkWriter.java](url)
- probabaly change _ANY_ to _DIRECTED_?
- also add a export option for directed networks

**Comment by srikanthBezawada** [comment]
Hi @moranges ,

Thanks for the feature request. We have updated the [app ](http://apps.cytoscape.org/apps/adjexporter)so that it can handle directed networks.

Suppose the network has 
nodes A, B, C & 
directed edges A->B, B->C. 
Output file will be like this.

NName   C   B   A  
C   0   -1  0  
B   1   0   -1  
A   0   1   0   
- If you don't want to have -1's as per your convention, you can do a text search of **-1** using a text editor and replace by **0**.
- Of course, you have the option to get a output file without node names. So, there are total 4 possiblities as shown [here](http://apps.cytoscape.org/media/adjexporter/screenshots/AdjExportFormats.png).

**Comment by moranges** [comment]
Thank you so much, @srikanthBezawada and @smd-faizan! Really appreciate it. I will get the update from the store and go from there, thanks again!!

**Comment by srikanthBezawada** [comment]
Hi @moranges ,

Can you please explain your use case ? Also feel free to approach us if you want to get any Cytoscape app developed.

**Comment by moranges** [comment]
Hi Srikanth,

Sure. I'm creating directed networks in Cytoscape and I need to export its adjacency matrix so I can compare it against another adjacency matrix that I'm getting out of a script I'm writing in R. That way I can learn the differences between both networks. 

Do you also support Cytoscape?

Thanks,

Mariano.

**Comment by srikanthBezawada** [comment]
@moranges , let us know how it goes. Is this academic work ?

Faizan and I develop Cytoscape apps and not Cytoscape core(so far) if that's what you meant ?

**Comment by moranges** [comment]
Sure I will. Basically I'm working on a thesis on network inference (machine learning) and I'm using Cytoscape along other tools to accomplish my goals there.

Yeap, that is what I meant. Nice work!

Thanks,

Mariano.

**Comment by srikanthBezawada** [comment]
@moranges , I've updated the app _again_ to fix [this bug](https://github.com/srikanthBezawada/AdjacencyMatrixExporter/issues/3). 

Go through these examples ([1](http://apps.cytoscape.org/media/adjexporter/screenshots/Example1.PNG), [2](http://apps.cytoscape.org/media/adjexporter/screenshots/Example2.PNG) and [3](http://apps.cytoscape.org/media/adjexporter/screenshots/Example3.PNG)) to be clear about the conventions used.

What do you infer by comparing adjacency matrices ?
and good luck with your thesis.
